[project]
name = "deeplss-forecast-workspace"
version = "0.1.0"
requires-python = ">=3.10,<3.13"
dependencies = [
    "simple-slurm", 
]


[dependency-groups]
dev = [
    "ipython",
    "jupyterlab",
    "pytest",
    "ruff",
    "ipykernel",
    "pudb",
    "memory-profiler",
    "tensorboard",
    "torch_tb_profiler",
]

build = [
    "scikit-build-core",
    "cmake",
    "ninja",
    "setuptools",
    "wheel",
]


[tool.uv.workspace]
members = [
    "repos/euclid-cosmogridv11",
    "repos/euclid-multiprobe-deeplss-training",
    "repos/euclid-multiprobe-simulation-forward-model",
    "repos/euclid-multiprobe-simulation-inference",
    "repos/FAST-PT",
    "repos/UFalcon",
    "repos/cuHPX",
]

[tool.uv.sources]
torch = { index = "pytorch-cu129" }
cuhpx = { workspace = true }

[[tool.uv.index]]
name = "pytorch-cu129"
url = "https://download.pytorch.org/whl/cu129"
explicit = true


[tool.uv]
no-build-isolation-package = ["torch-harmonics"]
override-dependencies = [
    "torch",
    "torchvision",
    "torchaudio",
]

